apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    chart: postgres-operator
    targetRevision: 1.14.0
    helm:
      releaseName: postgres-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
