apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 68.3.0
    helm:
      releaseName: monitoring
      values: |
        defaultRules:
          create: false
        crds:
          enabled: true
        alertmanager:
          enabled: false
        prometheus:
          enabled: true
        grafana:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx-internal
            hosts:
              - grafana.k8s.koa-dev.dev
            path: /
            tls:
            - secretName: grafana-tls
              hosts:
              - grafana.k8s.koa-dev.dev
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
